Add readme
Azure/RDS-Templates pull request #709
Opened 2022-10-12 21:25 UTC by shanberg1

2022-10-12 21:33 UTC, kkambow commented on ARM-wvd-templates/HCI/Readme.md
> +<a  href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fgithub.com%2FAzure%2FRDS-Templates%2Fblob%2Fmaster%2FARM-wvd-templates%2FHCI%2FQuickDeploy%2FCreateHciHostpoolQuickDepl
Can this deploy button come in the next link, alongside with Visualize button?
This link is not redirecting, I believe we need to give the raw github link here.

2022-10-12 21:34 UTC, kkambow commented on ARM-wvd-templates/HCI/Readme.md
> +<a  href="https://portal.azure.com/#create/Microsoft.Template/uri/https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/HCI/QuickDeploy/AddHciVirtualMachinesQuickDeployTemplate.json"
This link is not redirecting correctly, I believe we need to give the raw GitHub link here.

2022-10-13 14:48 UTC, kkambow commented on ARM-wvd-templates/HCI/Readme.md
> +<a  href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FRDS-Templates%2Fmaster%2FARM-wvd-templates%2FHCI%2FQuickDeploy%2FCreateHciHostpoolQ
Move the deploy to next line?

2022-10-13 17:08 UTC, kkambow commented on ARM-wvd-templates/HCI/Readme.md
> +<a  href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FRDS-Templates%2Fmaster%2FARM-wvd-templates%2FHCI%2FQuickDeploy%2FCreateHciHostpoolQ
The link should be for long-form template, not the quick deploy one.

2022-10-13 17:09 UTC, kkambow requested changes

2022-10-13 17:09 UTC, kkambow commented on ARM-wvd-templates/HCI/Readme.md
> +<a  href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FRDS-Templates%2Fmaster%2FARM-wvd-templates%2FHCI%2FQuickDeploy%2FAddHciVirtualMachi
The link should be for long-form template, not the quick deploy one.

2022-10-13 17:51 UTC, kkambow approved these changes

2022-10-13 17:55 UTC, walrusmcd approved these changes
looks great

2022-10-13 17:56 UTC, merged